### ISSUE TITLE
SMTP checks should run against all MX found only if there is a error.

### ISSUE THREAD

**Issue by AlexeyDemidov** [rubygarage/truemail#16]
SMTP checks are currently incorrectly run against all MX servers found while it should stop on the first successful `RCPT TO`. It should try the next MX only if the current MX failed with temporary error (connection timeout or refused, 4xx error). If the current MX returned 5xx error for any command (not only `RCPT TO`) then other MXs should not be attempted and validation should fail.

**Comment by bestwebua** [comment]
Alexey, thanks for your deep analyzing of Truemail. SMTP check stops if ```RCPT TO``` has been successful or fails, otherwise Truemail checks next mx. This behavior for cases when remote SMTP server has closed connection without QUIT command from client. Check your gem version. This feature has been implemented in the last two versions.
